### ISSUE TITLE
Add k8s sub-command to trivy

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/trivy-kubernetes#5]
Adding 2 k8s sub-commands to trivy project : 
 - creating a repo for kubernetre-trivy with github action and etc #4 
 - list resource  by namespace name #1 
 - list cluster resources #2 
 - [add sub-command on trivy](https://github.com/aquasecurity/trivy/issues/2062) 
 - add license #7

**Comment by josedonizetti** [comment]
- https://github.com/aquasecurity/trivy-kubernetes/issues/22
- https://github.com/aquasecurity/trivy/issues/2133
- https://github.com/aquasecurity/trivy/issues/2134
- https://github.com/aquasecurity/trivy/issues/2135
- https://github.com/aquasecurity/trivy/issues/2137
- https://github.com/aquasecurity/trivy/issues/2138

**Comment by josedonizetti** [comment]
Moved to https://github.com/aquasecurity/trivy/issues/2207
